### ISSUE TITLE
Feedback wird nicht mit übernommen (HTML) Export

### ISSUE THREAD

**Issue by LennartSpee** [webers-technikum-wien/moodle-qformat_printout#4]
Hello there,

first a huge thanks for developing this plugin.
Since a couple of month the availability to print out the feedback answers is not given anymore.
Is there any chance to use this great feature again?

Thanks,
Lennart

**Comment by stemiwe** [comment]
hi lennart,

i think you must be mixing it up with some other export plugin, as this one never included feedback, and i did not change the plugin ever since releasing it, except for one small bugfix

i will leave this issue open and try to include feedback in future versions

**Comment by LennartSpee** [comment]
Thanks for the quick response.
I am working and writing in the interest of my university HS Bochum.
It seems that last year one of my professors had contact with you and you found a helpful fix for the feedback issue. Thats why I am a bit confused. The fix must have been created in July and since you made the last commit in November/December maybe the fix got overwritten again? 
I hope I am not mixing up things.

Thanks for considering including the feedback!

Cheers,

Lennart

**Comment by stemiwe** [comment]
oh, you are right, sorry for the confusion and thanks for reminding me :)

there is a v1.02 on the moodle plugin directory that does exactly that - back then i did not update our local site since we did not need that feature

the v1.02 however had a wrong version number for the build, and because of this v1.01 without the feedback feature was still presented as the latest one at the plugins directory.

i now updated both git and the moodle plugin directory to v1.03, which fixes this and includes general feedback
